name: impaktfull_architecture
description: Shared architecture for Impaktfull Flutter projects.
version: 0.0.1
homepage: https://github.com/Impaktfull/flutter_architecture

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.1
  flutter:
    sdk: flutter
  dio: ^5.4.0
  gap: ^3.0.1
  get_it: ^7.6.4
  injectable: ^2.3.2
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  path: ^1.8.3
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  snacky: ^0.0.5
  sprintf: ^7.0.0
  synchronized: ^3.1.0+1
  tuple: ^2.0.2
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: