name: impaktfull_architecture
description: Shared architecture for Impaktfull Flutter projects.
version: 0.0.1
homepage: https://github.com/Impaktfull/flutter_architecture

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: